language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $token
  repo: /DEVCGDL/devcgdl.github.io
  github-url: https://github.com/DEVCGDL/devcgdl.github.io
  keep-history: true
   local_dir: build
  on:
    branch: master